### ISSUE TITLE
 Debian 11 => dependencies issue when dealing with Fingerbank.

### ISSUE THREAD

**Issue by JeGoi** [inverse-inc/ansible-packetfence#51]
```
Setting up fingerbank (4.3.2+20220823160915+620786098+0011+v4~3~2+bullseye1) ...
While trying to resolve method call fingerbank::Schema::Local->isa() can not locate package "DBIx::Class::Schema" yet it is 
mentioned in @fingerbank::Schema::Local::ISA (perhaps you forgot to load "DBIx::Class::Schema"?) at 
/usr/lib/x86_64-linux-gnu/perl5/5.32/Class/MOP/Class.pm line 957.
Can't locate object method "load_classes" via package "fingerbank::Schema::Local" at lib/fingerbank/Schema/Local.pm line 16. 
Compilation failed in require at db/upgrade.pl line 25. BEGIN failed--compilation aborted at db/upgrade.pl line 25.
chown: cannot access '/usr/local/fingerbank/db/fingerbank_Local.db': No such file or directory chmod: cannot access
 '/usr/local/fingerbank/db/fingerbank_Local.db': No such file or directory make: *** [Makefile:42: init-db-local] 
Error 1 dpkg: error processing package fingerbank (--configure): installed fingerbank package post-installation script subprocess returned error exit status 2
```

**Comment by JeGoi** [comment]
Solution:
"install_recommends: true"
into this file: packetfence_install/tasks/debian.yml
https://github.com/inverse-inc/ansible-packetfence/blob/master/packetfence/roles/packetfence_install/tasks/debian.yml#L18

With something like that:
```
- name: Install PacketFence from the repo
  apt:
    name: "{{ packetfence_install__deb_packages }}"
    state: "{{ packetfence_install__pkg_state }}"
    install_recommends: true
  register: packetfence_install__register_packages
```
